name: Download 3GPP TS

on:
  push:
    branches: [ "main" ]
    paths:
      - 'watchtower/dl.json'
  workflow_dispatch:

env:
  WORK_DIR: specifications

jobs:
  resources:
    name: Update resources
    runs-on: ubuntu-latest
    defaults:
      # working-directory only work for 'run' step
      run:
        working-directory: ${{ env.WORK_DIR }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          
      - name: Set Working Directory and Install
        run: pip install -r requirements.txt
      
      - name: Fetch resources
        run: python3 3gppDownloader.py
        
      - name: Update resources
        uses: test-room-7/action-update-file@v1.8.0
        with:
            file-path: ${{ env.WORK_DIR }}/*
            commit-msg: Update Json
            committer-name: kubedocker
            committer-email: kubedocker@outlook.com
            github-token: ${{ secrets.DL_TOKEN }}
